services:
  MinhaWeb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MinhaWeb-web
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - MinhaWeb-network
    labels:
      - "com.MinhaWeb.description=Landing page MinhaWeb"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  MinhaWeb-network:
    driver: bridge
